// ────────────────────────────────────────────────────────────
// Extended curated catalog. Merged into the seed arrays by data.ts.
// Organized as dupe clusters: one luxury "original" → its known dupes.
//
// NOTE: prices are approximate MSRP at time of curation and fluctuate —
// the scheduled refresh pipeline (scripts/refresh-prices.ts) keeps live
// prices current once a feed adapter is connected. Offer URLs are retailer
// search URLs, which resolve to the right product and accept affiliate
// wrapping. To grow further, add more clusters below.
// ────────────────────────────────────────────────────────────

import type { Brand, Product, Alternative, OfferSpec } from "./types";

const img = (id: string) => `/products/${id}.jpg`;

// ── New brands referenced by the extended catalog ──────────────
export const EXTRA_BRANDS: Brand[] = [
  // skincare
  { id: "sk-ii", name: "SK-II", category: "beauty", luxuryLevel: "luxury", country: "Japan", priceRange: "$$$" },
  { id: "missha", name: "Missha", category: "beauty", luxuryLevel: "budget", country: "South Korea", priceRange: "$" },
  { id: "cosrx", name: "COSRX", category: "beauty", luxuryLevel: "budget", country: "South Korea", priceRange: "$" },
  { id: "skinceuticals", name: "SkinCeuticals", category: "beauty", luxuryLevel: "luxury", country: "USA", priceRange: "$$$" },
  { id: "timeless", name: "Timeless Skin Care", category: "beauty", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "maelove", name: "Maelove", category: "beauty", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "sunday-riley", name: "Sunday Riley", category: "beauty", luxuryLevel: "luxury", country: "USA", priceRange: "$$$" },
  { id: "laneige", name: "Laneige", category: "beauty", luxuryLevel: "mid", country: "South Korea", priceRange: "$$" },
  { id: "vaseline", name: "Vaseline", category: "beauty", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  // makeup
  { id: "nars", name: "NARS", category: "beauty", luxuryLevel: "luxury", country: "USA", priceRange: "$$$" },
  { id: "maybelline", name: "Maybelline", category: "beauty", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "benefit", name: "Benefit Cosmetics", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "anastasia", name: "Anastasia Beverly Hills", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "too-faced", name: "Too Faced", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "essence", name: "essence", category: "beauty", luxuryLevel: "budget", country: "Germany", priceRange: "$" },
  { id: "tarte", name: "Tarte", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "rare-beauty", name: "Rare Beauty", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "milani", name: "Milani", category: "beauty", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "fenty", name: "Fenty Beauty", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  // hair
  { id: "moroccanoil", name: "Moroccanoil", category: "hair", luxuryLevel: "mid", country: "Israel", priceRange: "$$" },
  { id: "ogx", name: "OGX", category: "hair", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "briogeo", name: "Briogeo", category: "hair", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "gisou", name: "Gisou", category: "hair", luxuryLevel: "luxury", country: "Netherlands", priceRange: "$$$" },
  { id: "batiste", name: "Batiste", category: "hair", luxuryLevel: "budget", country: "UK", priceRange: "$" },
  // jewelry
  { id: "hermes", name: "Hermès", category: "jewelry", luxuryLevel: "luxury", country: "France", priceRange: "$$$$" },
  { id: "baublebar", name: "BaubleBar", category: "jewelry", luxuryLevel: "budget", country: "USA", priceRange: "$" },
];

// ── New products ───────────────────────────────────────────────
export const EXTRA_PRODUCTS: Product[] = [
  // ===== SKINCARE clusters =====
  {
    id: "sk2-essence", brandId: "sk-ii", brandName: "SK-II", name: "Facial Treatment Essence",
    category: "beauty", subcategory: "Essence", price: 99, image: img("sk2-essence"),
    rating: 4.6, reviewCount: 12800, isOriginal: true,
    description: "The cult 'miracle water' powered by PITERA™ to refine texture, tone, and radiance.",
    targetUser: "Dull, uneven skin wanting glass-skin glow",
    ingredients: ["Galactomyces Ferment Filtrate (PITERA)", "Butylene Glycol"],
    attributes: { brightening: true, hydration: 88, luxuryLevel: "High" },
    slug: "sk-ii-facial-treatment-essence",
  },
  {
    id: "missha-essence", brandId: "missha", brandName: "Missha", name: "Time Revolution The First Treatment Essence",
    category: "beauty", subcategory: "Essence", price: 30, image: img("missha-essence"),
    rating: 4.5, reviewCount: 9400,
    description: "Fermented essence that hydrates and brightens — the famous SK-II alternative.",
    targetUser: "Glow seekers on a budget",
    ingredients: ["Galactomyces Ferment Filtrate", "Niacinamide", "Adenosine"],
    attributes: { brightening: true, hydration: 85, luxuryLevel: "Budget" },
    slug: "missha-time-revolution-first-treatment-essence",
  },
  {
    id: "cosrx-galacto", brandId: "cosrx", brandName: "COSRX", name: "Galactomyces 95 Tone Balancing Essence",
    category: "beauty", subcategory: "Essence", price: 25, image: img("cosrx-galacto"),
    rating: 4.4, reviewCount: 8700,
    description: "95% galactomyces essence that balances tone and boosts radiance.",
    targetUser: "Uneven tone, budget-conscious K-beauty fans",
    ingredients: ["Galactomyces Ferment Filtrate 95%", "Niacinamide"],
    attributes: { brightening: true, hydration: 84, luxuryLevel: "Budget" },
    slug: "cosrx-galactomyces-95-essence",
  },
  {
    id: "skinceuticals-ceferulic", brandId: "skinceuticals", brandName: "SkinCeuticals", name: "C E Ferulic Vitamin C Serum",
    category: "beauty", subcategory: "Serum", price: 182, image: img("skinceuticals-ceferulic"),
    rating: 4.7, reviewCount: 15200, isOriginal: true,
    description: "The gold-standard antioxidant serum: 15% vitamin C, ferulic acid, and vitamin E.",
    targetUser: "Anti-aging and brightening, all skin types",
    ingredients: ["15% L-Ascorbic Acid", "Ferulic Acid", "Vitamin E"],
    attributes: { brightening: true, antiAging: true, luxuryLevel: "High" },
    slug: "skinceuticals-c-e-ferulic",
  },
  {
    id: "timeless-vitc", brandId: "timeless", brandName: "Timeless Skin Care", name: "20% Vitamin C + E Ferulic Acid Serum",
    category: "beauty", subcategory: "Serum", price: 25, image: img("timeless-vitc"),
    rating: 4.5, reviewCount: 14100,
    description: "Near-identical vitamin C/E/ferulic formula at a fraction of the price.",
    targetUser: "Brightening on a budget",
    ingredients: ["20% L-Ascorbic Acid", "Vitamin E", "Ferulic Acid"],
    attributes: { brightening: true, antiAging: true, luxuryLevel: "Budget" },
    slug: "timeless-20-vitamin-c-serum",
  },
  {
    id: "maelove-glowmaker", brandId: "maelove", brandName: "Maelove", name: "The Glow Maker Vitamin C Serum",
    category: "beauty", subcategory: "Serum", price: 30, image: img("maelove-glowmaker"),
    rating: 4.5, reviewCount: 11900,
    description: "Cult-favorite vitamin C, ferulic, and hyaluronic serum — the C E Ferulic dupe.",
    targetUser: "Glow seekers wanting prestige results for less",
    ingredients: ["15% Vitamin C", "Ferulic Acid", "Vitamin E", "Hyaluronic Acid"],
    attributes: { brightening: true, antiAging: true, luxuryLevel: "Budget" },
    slug: "maelove-glow-maker-vitamin-c-serum",
  },
  {
    id: "sunday-riley-goodgenes", brandId: "sunday-riley", brandName: "Sunday Riley", name: "Good Genes All-In-One Lactic Acid Treatment",
    category: "beauty", subcategory: "Serum", price: 85, image: img("sunday-riley-goodgenes"),
    rating: 4.6, reviewCount: 10300, isOriginal: true,
    description: "Lactic acid treatment that exfoliates, plumps, and brightens for instant glow.",
    targetUser: "Dull, textured skin wanting smoother tone",
    ingredients: ["Purified Grade Lactic Acid", "Licorice", "Lemongrass"],
    attributes: { exfoliating: true, brightening: true, luxuryLevel: "High" },
    slug: "sunday-riley-good-genes",
  },
  {
    id: "ordinary-lactic", brandId: "the-ordinary", brandName: "The Ordinary", name: "Lactic Acid 10% + HA",
    category: "beauty", subcategory: "Serum", price: 9, image: img("ordinary-lactic"),
    rating: 4.4, reviewCount: 18600,
    description: "Gentle 10% lactic acid exfoliant with hyaluronic acid for smoother, brighter skin.",
    targetUser: "Texture and tone, on a budget",
    ingredients: ["Lactic Acid 10%", "Hyaluronic Acid", "Tasmanian Pepperberry"],
    attributes: { exfoliating: true, brightening: true, luxuryLevel: "Budget" },
    slug: "the-ordinary-lactic-acid-10",
  },
  {
    id: "laneige-lipmask", brandId: "laneige", brandName: "Laneige", name: "Lip Sleeping Mask",
    category: "beauty", subcategory: "Lip Treatment", price: 24, image: img("laneige-lipmask"),
    rating: 4.7, reviewCount: 41200, isOriginal: true,
    description: "Overnight lip mask with berry mix and vitamin C for soft, plump lips by morning.",
    targetUser: "Dry, chapped lips",
    ingredients: ["Murumuru Seed Butter", "Shea Butter", "Vitamin C", "Berry Mix Complex"],
    attributes: { moisturizing: true, overnight: true, luxuryLevel: "Mid" },
    slug: "laneige-lip-sleeping-mask",
  },
  {
    id: "vaseline-lip", brandId: "vaseline", brandName: "Vaseline", name: "Lip Therapy Rosy Lips Balm",
    category: "beauty", subcategory: "Lip Treatment", price: 4, image: img("vaseline-lip"),
    rating: 4.6, reviewCount: 22500,
    description: "Classic petrolatum lip balm that seals in moisture overnight — a budget lip-mask alternative.",
    targetUser: "Dry lips, minimal budget",
    ingredients: ["Petrolatum", "Shea Butter", "Rosa Centifolia Flower Extract"],
    attributes: { moisturizing: true, overnight: true, luxuryLevel: "Budget" },
    slug: "vaseline-lip-therapy-rosy-lips",
  },

  // ===== MAKEUP clusters =====
  {
    id: "ct-flawless-filter", brandId: "charlotte-tilbury", brandName: "Charlotte Tilbury", name: "Hollywood Flawless Filter",
    category: "beauty", subcategory: "Complexion", price: 49, image: img("ct-flawless-filter"),
    rating: 4.6, reviewCount: 33400, isOriginal: true,
    description: "Hybrid complexion booster for a lit-from-within, soft-focus glow.",
    targetUser: "Anyone wanting a radiant, filtered finish",
    attributes: { finish: "Radiant", coverage: "Light", glow: true },
    slug: "charlotte-tilbury-hollywood-flawless-filter",
  },
  {
    id: "elf-halo-glow", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Halo Glow Liquid Filter",
    category: "beauty", subcategory: "Complexion", price: 15, image: img("elf-halo-glow"),
    rating: 4.6, reviewCount: 47800,
    description: "Viral radiant complexion booster — the Charlotte Tilbury Flawless Filter dupe.",
    targetUser: "Glowy-skin lovers on a budget",
    attributes: { finish: "Radiant", coverage: "Light", glow: true },
    slug: "elf-halo-glow-liquid-filter",
  },
  {
    id: "nars-rcc", brandId: "nars", brandName: "NARS", name: "Radiant Creamy Concealer",
    category: "beauty", subcategory: "Concealer", price: 32, image: img("nars-rcc"),
    rating: 4.6, reviewCount: 38900, isOriginal: true,
    description: "Cult medium-to-full coverage concealer with a luminous, natural finish.",
    targetUser: "Under-eyes and blemishes, radiant finish",
    attributes: { coverage: "Medium-Full", finish: "Radiant" },
    slug: "nars-radiant-creamy-concealer",
  },
  {
    id: "elf-camo-concealer", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "16HR Camo Concealer",
    category: "beauty", subcategory: "Concealer", price: 7, image: img("elf-camo-concealer"),
    rating: 4.5, reviewCount: 52300,
    description: "Full-coverage, long-wear concealer that rivals luxury formulas.",
    targetUser: "Full coverage on a budget",
    attributes: { coverage: "Full", finish: "Matte" },
    slug: "elf-16hr-camo-concealer",
  },
  {
    id: "maybelline-agerewind", brandId: "maybelline", brandName: "Maybelline", name: "Instant Age Rewind Eraser Concealer",
    category: "beauty", subcategory: "Concealer", price: 13, image: img("maybelline-agerewind"),
    rating: 4.5, reviewCount: 61200,
    description: "Iconic cushion-applicator concealer for brightened, smoothed under-eyes.",
    targetUser: "Under-eye brightening, drugstore favorite",
    attributes: { coverage: "Medium", finish: "Satin" },
    slug: "maybelline-instant-age-rewind-concealer",
  },
  {
    id: "tarte-shape-tape", brandId: "tarte", brandName: "Tarte", name: "Shape Tape Concealer",
    category: "beauty", subcategory: "Concealer", price: 32, image: img("tarte-shape-tape"),
    rating: 4.5, reviewCount: 44100, isOriginal: true,
    description: "The TikTok-famous full-coverage concealer that brightens and sculpts.",
    targetUser: "Maximum coverage and brightening",
    attributes: { coverage: "Full", finish: "Matte" },
    slug: "tarte-shape-tape-concealer",
  },
  {
    id: "benefit-hoola", brandId: "benefit", brandName: "Benefit Cosmetics", name: "Hoola Matte Bronzer",
    category: "beauty", subcategory: "Bronzer", price: 34, image: img("benefit-hoola"),
    rating: 4.7, reviewCount: 29800, isOriginal: true,
    description: "The original matte bronzer for a natural, sun-kissed contour.",
    targetUser: "Natural matte bronzing for fair-medium skin",
    attributes: { finish: "Matte", shade: "Neutral" },
    slug: "benefit-hoola-matte-bronzer",
  },
  {
    id: "elf-putty-bronzer", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Putty Bronzer",
    category: "beauty", subcategory: "Bronzer", price: 7, image: img("elf-putty-bronzer"),
    rating: 4.6, reviewCount: 35600,
    description: "Creamy putty-to-powder bronzer — the beloved Hoola dupe.",
    targetUser: "Matte bronzing on a budget",
    attributes: { finish: "Matte", shade: "Neutral" },
    slug: "elf-putty-bronzer",
  },
  {
    id: "abh-brow-wiz", brandId: "anastasia", brandName: "Anastasia Beverly Hills", name: "Brow Wiz",
    category: "beauty", subcategory: "Brow", price: 25, image: img("abh-brow-wiz"),
    rating: 4.6, reviewCount: 27400, isOriginal: true,
    description: "Ultra-fine retractable brow pencil for natural, hair-like strokes.",
    targetUser: "Precise, natural-looking brows",
    attributes: { finish: "Natural", precision: "High" },
    slug: "anastasia-brow-wiz",
  },
  {
    id: "nyx-microbrow", brandId: "nyx", brandName: "NYX", name: "Micro Brow Pencil",
    category: "beauty", subcategory: "Brow", price: 13, image: img("nyx-microbrow"),
    rating: 4.5, reviewCount: 31100,
    description: "Slim dual-ended brow pencil with spoolie — a Brow Wiz alternative.",
    targetUser: "Defined brows for less",
    attributes: { finish: "Natural", precision: "High" },
    slug: "nyx-micro-brow-pencil",
  },
  {
    id: "elf-brow-pencil", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Instant Lift Brow Pencil",
    category: "beauty", subcategory: "Brow", price: 4, image: img("elf-brow-pencil"),
    rating: 4.4, reviewCount: 24800,
    description: "Angled brow pencil with spoolie for quick, natural definition.",
    targetUser: "Everyday brows, lowest budget",
    attributes: { finish: "Natural", precision: "Medium" },
    slug: "elf-instant-lift-brow-pencil",
  },
  {
    id: "tf-bts-mascara", brandId: "too-faced", brandName: "Too Faced", name: "Better Than Sex Mascara",
    category: "beauty", subcategory: "Mascara", price: 29, image: img("tf-bts-mascara"),
    rating: 4.5, reviewCount: 40200, isOriginal: true,
    description: "Hourglass-brush mascara for dramatic volume and curl.",
    targetUser: "Volume and drama lovers",
    attributes: { effect: "Volumizing", finish: "Dramatic" },
    slug: "too-faced-better-than-sex-mascara",
  },
  {
    id: "essence-lash-princess", brandId: "essence", brandName: "essence", name: "Lash Princess False Lash Effect Mascara",
    category: "beauty", subcategory: "Mascara", price: 5, image: img("essence-lash-princess"),
    rating: 4.5, reviewCount: 88900,
    description: "The viral $5 mascara delivering false-lash volume — a Better Than Sex dupe.",
    targetUser: "Dramatic lashes, tiny budget",
    attributes: { effect: "Volumizing", finish: "Dramatic" },
    slug: "essence-lash-princess-mascara",
  },
  {
    id: "loreal-lash-paradise", brandId: "loreal", brandName: "L'Oréal Paris", name: "Voluminous Lash Paradise Mascara",
    category: "beauty", subcategory: "Mascara", price: 12, image: img("loreal-lash-paradise"),
    rating: 4.4, reviewCount: 51700,
    description: "Soft-wavy brush mascara for voluptuous volume and length.",
    targetUser: "Full, fluttery lashes for less",
    attributes: { effect: "Volumizing", finish: "Dramatic" },
    slug: "loreal-voluminous-lash-paradise",
  },
  {
    id: "rare-soft-pinch", brandId: "rare-beauty", brandName: "Rare Beauty", name: "Soft Pinch Liquid Blush",
    category: "beauty", subcategory: "Blush", price: 23, image: img("rare-soft-pinch"),
    rating: 4.7, reviewCount: 36900, isOriginal: true,
    description: "Highly pigmented, blendable liquid blush for a natural flush. A little goes a long way.",
    targetUser: "Long-lasting, buildable color",
    attributes: { finish: "Natural", pigmentation: "High" },
    slug: "rare-beauty-soft-pinch-liquid-blush",
  },
  {
    id: "milani-cheek-kiss", brandId: "milani", brandName: "Milani", name: "Cheek Kiss Liquid Blush",
    category: "beauty", subcategory: "Blush", price: 11, image: img("milani-cheek-kiss"),
    rating: 4.4, reviewCount: 14200,
    description: "Pigmented, dewy liquid blush — a wallet-friendly Soft Pinch alternative.",
    targetUser: "Liquid blush lovers on a budget",
    attributes: { finish: "Dewy", pigmentation: "High" },
    slug: "milani-cheek-kiss-liquid-blush",
  },
  {
    id: "elf-liquid-blush", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Camo Liquid Blush",
    category: "beauty", subcategory: "Blush", price: 7, image: img("elf-liquid-blush"),
    rating: 4.5, reviewCount: 19800,
    description: "Pigmented, long-wear liquid blush for a natural flush at the lowest price.",
    targetUser: "Buildable blush, smallest budget",
    attributes: { finish: "Natural", pigmentation: "High" },
    slug: "elf-camo-liquid-blush",
  },
  {
    id: "fenty-gloss-bomb", brandId: "fenty", brandName: "Fenty Beauty", name: "Gloss Bomb Universal Lip Luminizer",
    category: "beauty", subcategory: "Lip Gloss", price: 21, image: img("fenty-gloss-bomb"),
    rating: 4.7, reviewCount: 45600, isOriginal: true,
    description: "Non-sticky, high-shine universal gloss in the iconic Fenty Glow shade.",
    targetUser: "Everyone wanting explosive shine",
    attributes: { finish: "Glossy", moisturizing: true },
    slug: "fenty-gloss-bomb-lip-luminizer",
  },

  // ===== HAIR clusters =====
  {
    id: "moroccanoil-treatment", brandId: "moroccanoil", brandName: "Moroccanoil", name: "Moroccanoil Treatment",
    category: "hair", subcategory: "Oil", price: 48, image: img("moroccanoil-treatment"),
    rating: 4.7, reviewCount: 33800, isOriginal: true,
    description: "The original argan-oil treatment for shine, softness, and frizz control.",
    targetUser: "All hair types wanting shine and smoothing",
    ingredients: ["Argan Oil", "Linseed Extract", "Vitamin E"],
    attributes: { shine: 92, frizzControl: true },
    slug: "moroccanoil-treatment",
  },
  {
    id: "ogx-argan", brandId: "ogx", brandName: "OGX", name: "Renewing + Argan Oil of Morocco Penetrating Oil",
    category: "hair", subcategory: "Oil", price: 9, image: img("ogx-argan"),
    rating: 4.5, reviewCount: 29400,
    description: "Lightweight argan oil for shine and frizz control — the Moroccanoil dupe.",
    targetUser: "Shine and smoothing on a budget",
    ingredients: ["Argan Oil", "Vitamin E"],
    attributes: { shine: 85, frizzControl: true },
    slug: "ogx-argan-oil-of-morocco-penetrating-oil",
  },
  {
    id: "olaplex-4", brandId: "olaplex", brandName: "Olaplex", name: "No.4 Bond Maintenance Shampoo",
    category: "hair", subcategory: "Shampoo", price: 30, image: img("olaplex-4"),
    rating: 4.6, reviewCount: 21500, isOriginal: true,
    description: "Reparative, hydrating shampoo that relinks broken bonds while cleansing.",
    targetUser: "Damaged and color-treated hair",
    ingredients: ["Bis-Aminopropyl Diglycol Dimaleate", "Sodium Cocoyl Isethionate"],
    attributes: { bondBuilding: true, repairLevel: 88, vegan: true },
    slug: "olaplex-no4-bond-maintenance-shampoo",
  },
  {
    id: "loreal-elvive-bond", brandId: "loreal", brandName: "L'Oréal Paris", name: "Elvive Bond Repair Shampoo",
    category: "hair", subcategory: "Shampoo", price: 11, image: img("loreal-elvive-bond"),
    rating: 4.3, reviewCount: 9600,
    description: "Bond-strengthening shampoo with citric acid — an affordable bond-repair option.",
    targetUser: "Weakened, damaged hair on a budget",
    ingredients: ["Citric Acid", "Bonding Care Complex"],
    attributes: { bondBuilding: true, repairLevel: 80, vegan: true },
    slug: "loreal-elvive-bond-repair-shampoo",
  },
  {
    id: "living-proof-dryshampoo", brandId: "living-proof", brandName: "Living Proof", name: "Perfect Hair Day (PhD) Dry Shampoo",
    category: "hair", subcategory: "Dry Shampoo", price: 28, image: img("living-proof-dryshampoo"),
    rating: 4.6, reviewCount: 18900, isOriginal: true,
    description: "Residue-free dry shampoo that absorbs oil, sweat, and odor for a clean refresh.",
    targetUser: "Second-day hair, oily roots",
    ingredients: ["Patented Healthy Hair Molecule (OFPMA)", "Witch Hazel"],
    attributes: { oilAbsorbing: true, residueFree: true },
    slug: "living-proof-phd-dry-shampoo",
  },
  {
    id: "batiste-dryshampoo", brandId: "batiste", brandName: "Batiste", name: "Original Dry Shampoo",
    category: "hair", subcategory: "Dry Shampoo", price: 9, image: img("batiste-dryshampoo"),
    rating: 4.5, reviewCount: 47300,
    description: "The best-selling dry shampoo for instant oil absorption and volume.",
    targetUser: "Quick refresh on a budget",
    ingredients: ["Rice Starch", "Fragrance"],
    attributes: { oilAbsorbing: true, residueFree: false },
    slug: "batiste-original-dry-shampoo",
  },
  {
    id: "briogeo-mask", brandId: "briogeo", brandName: "Briogeo", name: "Don't Despair, Repair! Deep Conditioning Mask",
    category: "hair", subcategory: "Mask", price: 38, image: img("briogeo-mask"),
    rating: 4.6, reviewCount: 16700, isOriginal: true,
    description: "Rich repair mask with rosehip and argan oils for dry, damaged hair.",
    targetUser: "Dry, damaged, or over-processed hair",
    ingredients: ["Rosehip Oil", "Argan Oil", "Algae Extract", "B-Vitamins"],
    attributes: { repairLevel: 90, hydration: 90 },
    slug: "briogeo-dont-despair-repair-mask",
  },
  {
    id: "ogx-coconut-mask", brandId: "ogx", brandName: "OGX", name: "Coconut Miracle Oil Extra Strength Hair Mask",
    category: "hair", subcategory: "Mask", price: 9, image: img("ogx-coconut-mask"),
    rating: 4.4, reviewCount: 13200,
    description: "Deep-conditioning coconut and argan mask for softness and repair on a budget.",
    targetUser: "Dry hair wanting affordable deep conditioning",
    ingredients: ["Coconut Oil", "Argan Oil", "Shea Butter"],
    attributes: { repairLevel: 78, hydration: 85 },
    slug: "ogx-coconut-miracle-oil-hair-mask",
  },
  {
    id: "gisou-hairoil", brandId: "gisou", brandName: "Gisou", name: "Honey Infused Hair Oil",
    category: "hair", subcategory: "Oil", price: 48, image: img("gisou-hairoil"),
    rating: 4.5, reviewCount: 14900, isOriginal: true,
    description: "Luxe honey and argan oil blend for nourished, glossy, frizz-free hair.",
    targetUser: "Dry, dull hair wanting glossy nourishment",
    ingredients: ["Mirsalehi Honey", "Argan Oil", "Vitamin E"],
    attributes: { shine: 90, frizzControl: true },
    slug: "gisou-honey-infused-hair-oil",
  },

  // ===== JEWELRY clusters =====
  {
    id: "hermes-clic-h", brandId: "hermes", brandName: "Hermès", name: "Clic H Bracelet",
    category: "jewelry", subcategory: "Bracelet", price: 680, image: img("hermes-clic-h"),
    rating: 4.8, reviewCount: 1200, isOriginal: true,
    description: "Iconic enamel-and-gold-plated bangle with the signature H clasp.",
    targetUser: "Logo-luxury lovers",
    attributes: { metal: "Gold Plated + Enamel", style: "Logo", occasion: "Everyday/Gift" },
    slug: "hermes-clic-h-bracelet",
  },
  {
    id: "baublebar-enamel-bangle", brandId: "baublebar", brandName: "BaubleBar", name: "Gabriela Enamel Bracelet",
    category: "jewelry", subcategory: "Bracelet", price: 48, image: img("baublebar-enamel-bangle"),
    rating: 4.3, reviewCount: 2100,
    description: "Colorful enamel bangle with a gold-tone clasp — a Clic H-inspired look.",
    targetUser: "Pop-of-color stackers on a budget",
    attributes: { metal: "Gold Plated + Enamel", style: "Logo", occasion: "Everyday" },
    slug: "baublebar-gabriela-enamel-bracelet",
  },
  {
    id: "cartier-juste-un-clou", brandId: "cartier", brandName: "Cartier", name: "Juste un Clou Bracelet",
    category: "jewelry", subcategory: "Bracelet", price: 4050, image: img("cartier-juste-un-clou"),
    rating: 4.9, reviewCount: 980, isOriginal: true,
    description: "The nail-motif bracelet that turns an everyday object into an icon.",
    targetUser: "Edgy luxury collectors",
    attributes: { metal: "18k Gold", style: "Nail", occasion: "Everyday/Gift" },
    slug: "cartier-juste-un-clou-bracelet",
  },
  {
    id: "baublebar-nail-cuff", brandId: "baublebar", brandName: "BaubleBar", name: "Nail Wrap Cuff Bracelet",
    category: "jewelry", subcategory: "Bracelet", price: 44, image: img("baublebar-nail-cuff"),
    rating: 4.2, reviewCount: 1500,
    description: "Gold-tone nail-wrap cuff — a Juste un Clou-inspired everyday piece.",
    targetUser: "Edgy minimalists on a budget",
    attributes: { metal: "Gold Plated", style: "Nail", occasion: "Everyday" },
    slug: "baublebar-nail-wrap-cuff",
  },
  {
    id: "vca-sweet-earrings", brandId: "vancleef", brandName: "Van Cleef & Arpels", name: "Sweet Alhambra Earrings",
    category: "jewelry", subcategory: "Earrings", price: 2050, image: img("vca-sweet-earrings"),
    rating: 4.9, reviewCount: 760, isOriginal: true,
    description: "Petite clover-motif studs in 18k gold and mother-of-pearl.",
    targetUser: "Quiet-luxury collectors",
    attributes: { metal: "18k Gold", style: "Clover", occasion: "Everyday/Gift" },
    slug: "van-cleef-sweet-alhambra-earrings",
  },
  {
    id: "gorjana-clover-studs", brandId: "gorjana", brandName: "Gorjana", name: "Lou Mother-of-Pearl Studs",
    category: "jewelry", subcategory: "Earrings", price: 50, image: img("gorjana-clover-studs"),
    rating: 4.4, reviewCount: 1100,
    description: "Dainty mother-of-pearl clover studs in 18k gold plating — an Alhambra-inspired pick.",
    targetUser: "Everyday clover-stud lovers",
    attributes: { metal: "18k Gold Plated", style: "Clover", occasion: "Everyday" },
    slug: "gorjana-lou-mother-of-pearl-studs",
  },
];

// ── New offers (search URLs; affiliate-wrapped at render/ingest) ──
const a = (q: string) => `https://www.amazon.com/s?k=${encodeURIComponent(q)}`;
const seph = (q: string) => `https://www.sephora.com/search?keyword=${encodeURIComponent(q)}`;
const ulta = (q: string) => `https://www.ulta.com/shop/search?Ntt=${encodeURIComponent(q)}`;
const tgt = (q: string) => `https://www.target.com/s?searchTerm=${encodeURIComponent(q)}`;
const nord = (q: string) => `https://www.nordstrom.com/sr?keyword=${encodeURIComponent(q)}`;

export const EXTRA_OFFER_SPECS: Record<string, OfferSpec[]> = {
  "sk2-essence": [{ retailerId: "sephora", url: seph("sk-ii facial treatment essence"), price: 99 }, { retailerId: "nordstrom", url: nord("sk-ii facial treatment essence"), price: 99 }],
  "missha-essence": [{ retailerId: "amazon", url: a("Missha Time Revolution First Treatment Essence"), price: 30 }],
  "cosrx-galacto": [{ retailerId: "amazon", url: a("COSRX Galactomyces 95 Essence"), price: 25 }, { retailerId: "ulta", url: ulta("cosrx galactomyces"), price: 25 }],
  "skinceuticals-ceferulic": [{ retailerId: "amazon", url: a("SkinCeuticals C E Ferulic"), price: 182 }],
  "timeless-vitc": [{ retailerId: "amazon", url: a("Timeless 20% Vitamin C E Ferulic Serum"), price: 25 }],
  "maelove-glowmaker": [{ retailerId: "amazon", url: a("Maelove Glow Maker Vitamin C Serum"), price: 30 }],
  "sunday-riley-goodgenes": [{ retailerId: "sephora", url: seph("sunday riley good genes"), price: 85 }],
  "ordinary-lactic": [{ retailerId: "sephora", url: seph("the ordinary lactic acid 10"), price: 9 }, { retailerId: "ulta", url: ulta("the ordinary lactic acid"), price: 9 }],
  "laneige-lipmask": [{ retailerId: "sephora", url: seph("laneige lip sleeping mask"), price: 24 }, { retailerId: "amazon", url: a("Laneige Lip Sleeping Mask"), price: 24 }],
  "vaseline-lip": [{ retailerId: "target", url: tgt("vaseline lip therapy rosy"), price: 4 }, { retailerId: "amazon", url: a("Vaseline Lip Therapy Rosy Lips"), price: 4 }],

  "ct-flawless-filter": [{ retailerId: "sephora", url: seph("charlotte tilbury flawless filter"), price: 49 }],
  "elf-halo-glow": [{ retailerId: "target", url: tgt("elf halo glow liquid filter"), price: 15 }, { retailerId: "ulta", url: ulta("elf halo glow"), price: 15 }],
  "nars-rcc": [{ retailerId: "sephora", url: seph("nars radiant creamy concealer"), price: 32 }],
  "elf-camo-concealer": [{ retailerId: "target", url: tgt("elf 16hr camo concealer"), price: 7 }, { retailerId: "amazon", url: a("elf 16HR Camo Concealer"), price: 7 }],
  "maybelline-agerewind": [{ retailerId: "target", url: tgt("maybelline instant age rewind concealer"), price: 13 }, { retailerId: "amazon", url: a("Maybelline Instant Age Rewind Concealer"), price: 13 }],
  "tarte-shape-tape": [{ retailerId: "sephora", url: seph("tarte shape tape concealer"), price: 32 }, { retailerId: "ulta", url: ulta("tarte shape tape"), price: 32 }],
  "benefit-hoola": [{ retailerId: "sephora", url: seph("benefit hoola bronzer"), price: 34 }],
  "elf-putty-bronzer": [{ retailerId: "target", url: tgt("elf putty bronzer"), price: 7 }, { retailerId: "amazon", url: a("elf Putty Bronzer"), price: 7 }],
  "abh-brow-wiz": [{ retailerId: "sephora", url: seph("anastasia brow wiz"), price: 25 }],
  "nyx-microbrow": [{ retailerId: "ulta", url: ulta("nyx micro brow pencil"), price: 13 }, { retailerId: "amazon", url: a("NYX Micro Brow Pencil"), price: 13 }],
  "elf-brow-pencil": [{ retailerId: "target", url: tgt("elf instant lift brow pencil"), price: 4 }],
  "tf-bts-mascara": [{ retailerId: "sephora", url: seph("too faced better than sex mascara"), price: 29 }],
  "essence-lash-princess": [{ retailerId: "amazon", url: a("essence Lash Princess Mascara"), price: 5 }, { retailerId: "target", url: tgt("essence lash princess mascara"), price: 5 }],
  "loreal-lash-paradise": [{ retailerId: "target", url: tgt("loreal lash paradise mascara"), price: 12 }, { retailerId: "amazon", url: a("LOreal Voluminous Lash Paradise"), price: 12 }],
  "rare-soft-pinch": [{ retailerId: "sephora", url: seph("rare beauty soft pinch liquid blush"), price: 23 }],
  "milani-cheek-kiss": [{ retailerId: "amazon", url: a("Milani Cheek Kiss Liquid Blush"), price: 11 }, { retailerId: "target", url: tgt("milani cheek kiss blush"), price: 11 }],
  "elf-liquid-blush": [{ retailerId: "target", url: tgt("elf camo liquid blush"), price: 7 }],
  "fenty-gloss-bomb": [{ retailerId: "sephora", url: seph("fenty gloss bomb"), price: 21 }],

  "moroccanoil-treatment": [{ retailerId: "sephora", url: seph("moroccanoil treatment"), price: 48 }, { retailerId: "ulta", url: ulta("moroccanoil treatment"), price: 48 }],
  "ogx-argan": [{ retailerId: "target", url: tgt("ogx argan oil of morocco penetrating oil"), price: 9 }, { retailerId: "amazon", url: a("OGX Argan Oil of Morocco Penetrating Oil"), price: 9 }],
  "olaplex-4": [{ retailerId: "sephora", url: seph("olaplex no 4 shampoo"), price: 30 }, { retailerId: "amazon", url: a("Olaplex No 4 Bond Maintenance Shampoo"), price: 30 }],
  "loreal-elvive-bond": [{ retailerId: "target", url: tgt("loreal elvive bond repair shampoo"), price: 11 }],
  "living-proof-dryshampoo": [{ retailerId: "sephora", url: seph("living proof dry shampoo"), price: 28 }],
  "batiste-dryshampoo": [{ retailerId: "target", url: tgt("batiste original dry shampoo"), price: 9 }, { retailerId: "amazon", url: a("Batiste Original Dry Shampoo"), price: 9 }],
  "briogeo-mask": [{ retailerId: "sephora", url: seph("briogeo dont despair repair mask"), price: 38 }],
  "ogx-coconut-mask": [{ retailerId: "amazon", url: a("OGX Coconut Miracle Oil Hair Mask"), price: 9 }],
  "gisou-hairoil": [{ retailerId: "sephora", url: seph("gisou honey infused hair oil"), price: 48 }],

  "hermes-clic-h": [{ retailerId: "nordstrom", url: nord("hermes clic h bracelet"), price: 680 }],
  "baublebar-enamel-bangle": [{ retailerId: "amazon", url: a("BaubleBar enamel bangle bracelet"), price: 48 }],
  "cartier-juste-un-clou": [{ retailerId: "amazon", url: a("Cartier Juste un Clou bracelet"), price: 4050 }],
  "baublebar-nail-cuff": [{ retailerId: "amazon", url: a("nail wrap cuff bracelet gold"), price: 44 }],
  "vca-sweet-earrings": [{ retailerId: "amazon", url: a("Van Cleef Sweet Alhambra earrings"), price: 2050 }],
  "gorjana-clover-studs": [{ retailerId: "amazon", url: a("Gorjana Lou mother of pearl studs"), price: 50 }],
};

// ── New dupe relationships ─────────────────────────────────────
export const EXTRA_ALTERNATIVES: Record<string, Alternative[]> = {
  "sk2-essence": [
    { productId: "missha-essence", matchScore: 90, dupeLevel: "similar", reason: "Same galactomyces ferment hero, ~3× cheaper" },
    { productId: "cosrx-galacto", matchScore: 86, dupeLevel: "budget", reason: "95% galactomyces essence at a fraction of the price" },
  ],
  "skinceuticals-ceferulic": [
    { productId: "maelove-glowmaker", matchScore: 89, dupeLevel: "budget", reason: "Vitamin C + ferulic + E blend, ~6× cheaper" },
    { productId: "timeless-vitc", matchScore: 88, dupeLevel: "budget", reason: "Near-identical L-ascorbic/ferulic/E formula" },
  ],
  "sunday-riley-goodgenes": [
    { productId: "ordinary-lactic", matchScore: 87, dupeLevel: "budget", reason: "Lactic-acid exfoliation for under $10" },
  ],
  "laneige-lipmask": [
    { productId: "vaseline-lip", matchScore: 80, dupeLevel: "budget", reason: "Occlusive overnight lip moisture for a few dollars" },
  ],
  "ct-flawless-filter": [
    { productId: "elf-halo-glow", matchScore: 92, dupeLevel: "budget", reason: "The viral radiant-filter dupe, ~3× cheaper" },
  ],
  "nars-rcc": [
    { productId: "elf-camo-concealer", matchScore: 88, dupeLevel: "budget", reason: "Long-wear radiant-to-natural coverage for $7" },
    { productId: "maybelline-agerewind", matchScore: 84, dupeLevel: "budget", reason: "Brightening under-eye coverage, drugstore icon" },
  ],
  "tarte-shape-tape": [
    { productId: "elf-camo-concealer", matchScore: 87, dupeLevel: "budget", reason: "Full-coverage matte finish at a fraction of the price" },
    { productId: "maybelline-agerewind", matchScore: 82, dupeLevel: "budget", reason: "Brightens and covers, beloved drugstore pick" },
  ],
  "benefit-hoola": [
    { productId: "elf-putty-bronzer", matchScore: 90, dupeLevel: "budget", reason: "Matte neutral bronzing for $7 — the classic dupe" },
  ],
  "abh-brow-wiz": [
    { productId: "nyx-microbrow", matchScore: 88, dupeLevel: "budget", reason: "Fine-tip natural brow definition for half the price" },
    { productId: "elf-brow-pencil", matchScore: 83, dupeLevel: "budget", reason: "Angled spoolie pencil for everyday brows, $4" },
  ],
  "tf-bts-mascara": [
    { productId: "essence-lash-princess", matchScore: 89, dupeLevel: "budget", reason: "False-lash volume for $5 — the famous dupe" },
    { productId: "loreal-lash-paradise", matchScore: 85, dupeLevel: "budget", reason: "Voluptuous volume and length, drugstore favorite" },
  ],
  "rare-soft-pinch": [
    { productId: "milani-cheek-kiss", matchScore: 87, dupeLevel: "budget", reason: "Pigmented liquid blush, dewy flush for half the price" },
    { productId: "elf-liquid-blush", matchScore: 84, dupeLevel: "budget", reason: "Buildable liquid color for $7" },
  ],
  "fenty-gloss-bomb": [
    { productId: "nyx-butter", matchScore: 85, dupeLevel: "budget", reason: "Non-sticky high-shine gloss for under $10" },
  ],
  "moroccanoil-treatment": [
    { productId: "ogx-argan", matchScore: 86, dupeLevel: "budget", reason: "Argan-oil shine and frizz control, ~5× cheaper" },
  ],
  "olaplex-4": [
    { productId: "loreal-elvive-bond", matchScore: 83, dupeLevel: "budget", reason: "Bond-repair cleansing with citric acid, drugstore price" },
  ],
  "living-proof-dryshampoo": [
    { productId: "batiste-dryshampoo", matchScore: 82, dupeLevel: "budget", reason: "Instant oil absorption for a third of the price" },
  ],
  "briogeo-mask": [
    { productId: "ogx-coconut-mask", matchScore: 84, dupeLevel: "budget", reason: "Deep coconut/argan conditioning, ~4× cheaper" },
  ],
  "gisou-hairoil": [
    { productId: "verb-ghost-oil", matchScore: 83, dupeLevel: "budget", reason: "Lightweight nourishing shine for less" },
    { productId: "ogx-argan", matchScore: 80, dupeLevel: "budget", reason: "Glossy, frizz-smoothing oil at a budget price" },
  ],
  "hermes-clic-h": [
    { productId: "baublebar-enamel-bangle", matchScore: 85, dupeLevel: "budget", reason: "Enamel-and-gold bangle look for a fraction of the price" },
  ],
  "cartier-juste-un-clou": [
    { productId: "baublebar-nail-cuff", matchScore: 83, dupeLevel: "budget", reason: "Nail-motif cuff capturing the icon for under $50" },
  ],
  "vca-sweet-earrings": [
    { productId: "gorjana-clover-studs", matchScore: 86, dupeLevel: "budget", reason: "Mother-of-pearl clover studs, fine-jewelry feel for less" },
  ],
};
