// ────────────────────────────────────────────────────────────
// Extended curated catalog — batch 2. Merged into the seed arrays by
// data.ts (same pattern as catalog-extended.ts). More real dupe clusters
// across skincare, makeup, hair tools, and jewelry.
//
// Prices ~MSRP at curation; refresh pipeline keeps live prices current.
// Offer URLs are retailer search URLs (affiliate-wrapped at render/ingest).
// ────────────────────────────────────────────────────────────

import type { Brand, Product, Alternative, OfferSpec } from "./types";

const img = (id: string) => `/products/${id}.svg`;

export const EXTRA2_BRANDS: Brand[] = [
  { id: "paulas-choice", name: "Paula's Choice", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "supergoop", name: "Supergoop!", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "summer-fridays", name: "Summer Fridays", category: "beauty", luxuryLevel: "luxury", country: "USA", priceRange: "$$$" },
  { id: "farmacy", name: "Farmacy", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "banila-co", name: "Banila Co", category: "beauty", luxuryLevel: "budget", country: "South Korea", priceRange: "$" },
  { id: "urban-decay", name: "Urban Decay", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "laura-mercier", name: "Laura Mercier", category: "beauty", luxuryLevel: "luxury", country: "USA", priceRange: "$$$" },
  { id: "coty", name: "Coty", category: "beauty", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "mac", name: "MAC Cosmetics", category: "beauty", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "dyson", name: "Dyson", category: "hair", luxuryLevel: "luxury", country: "UK", priceRange: "$$$" },
  { id: "shark", name: "Shark Beauty", category: "hair", luxuryLevel: "mid", country: "USA", priceRange: "$$" },
  { id: "revlon", name: "Revlon", category: "hair", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "fanola", name: "Fanola", category: "hair", luxuryLevel: "budget", country: "Italy", priceRange: "$" },
  { id: "mielle", name: "Mielle Organics", category: "hair", luxuryLevel: "budget", country: "USA", priceRange: "$" },
  { id: "color-wow", name: "Color Wow", category: "hair", luxuryLevel: "mid", country: "UK", priceRange: "$$" },
  { id: "jennifer-fisher", name: "Jennifer Fisher", category: "jewelry", luxuryLevel: "luxury", country: "USA", priceRange: "$$$" },
  { id: "kay", name: "Kay Jewelers", category: "jewelry", luxuryLevel: "mid", country: "USA", priceRange: "$$$" },
];

export const EXTRA2_PRODUCTS: Product[] = [
  // ===== SKINCARE =====
  {
    id: "paulas-choice-bha", brandId: "paulas-choice", brandName: "Paula's Choice", name: "Skin Perfecting 2% BHA Liquid Exfoliant",
    category: "beauty", subcategory: "Exfoliant", price: 35, image: img("paulas-choice-bha"),
    rating: 4.7, reviewCount: 41200, isOriginal: true,
    description: "Cult salicylic-acid liquid that unclogs pores and smooths texture.",
    targetUser: "Congested, bumpy, or blackhead-prone skin",
    ingredients: ["Salicylic Acid 2%", "Green Tea Extract", "Methylpropanediol"],
    attributes: { exfoliating: true, poreCare: true },
    slug: "paulas-choice-2-bha-liquid-exfoliant",
  },
  {
    id: "cosrx-bha", brandId: "cosrx", brandName: "COSRX", name: "BHA Blackhead Power Liquid",
    category: "beauty", subcategory: "Exfoliant", price: 25, image: img("cosrx-bha"),
    rating: 4.4, reviewCount: 12800,
    description: "Gentle BHA exfoliant with niacinamide to clear and refine pores.",
    targetUser: "Blackheads and texture, budget-friendly",
    ingredients: ["Betaine Salicylate 4%", "Niacinamide"],
    attributes: { exfoliating: true, poreCare: true },
    slug: "cosrx-bha-blackhead-power-liquid",
  },
  {
    id: "supergoop-glowscreen", brandId: "supergoop", brandName: "Supergoop!", name: "Glowscreen SPF 40",
    category: "beauty", subcategory: "Sunscreen", price: 38, image: img("supergoop-glowscreen"),
    rating: 4.5, reviewCount: 24100, isOriginal: true,
    description: "Glowy SPF 40 primer-sunscreen with hyaluronic acid and niacinamide.",
    targetUser: "Daily glow + sun protection",
    ingredients: ["Niacinamide", "Hyaluronic Acid", "Vitamin B5"],
    attributes: { spf: 40, glow: true },
    slug: "supergoop-glowscreen-spf-40",
  },
  {
    id: "elf-whoa-glow", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Suntouchable! Whoa Glow SPF 30",
    category: "beauty", subcategory: "Sunscreen", price: 14, image: img("elf-whoa-glow"),
    rating: 4.5, reviewCount: 19600,
    description: "Glowy SPF 30 sunscreen-primer — the viral Glowscreen dupe.",
    targetUser: "Dewy SPF on a budget",
    ingredients: ["Niacinamide", "Hyaluronic Acid"],
    attributes: { spf: 30, glow: true },
    slug: "elf-suntouchable-whoa-glow-spf-30",
  },
  {
    id: "summer-fridays-jetlag", brandId: "summer-fridays", brandName: "Summer Fridays", name: "Jet Lag Mask",
    category: "beauty", subcategory: "Moisturizer", price: 49, image: img("summer-fridays-jetlag"),
    rating: 4.5, reviewCount: 16800, isOriginal: true,
    description: "Hydrating moisturizing mask for dewy, refreshed skin anytime.",
    targetUser: "Dull, dehydrated, tired-looking skin",
    ingredients: ["Niacinamide", "Vitamin C", "Ceramides"],
    attributes: { hydration: 90, luxuryLevel: "High" },
    slug: "summer-fridays-jet-lag-mask",
  },
  {
    id: "elf-holy-hydration-cream", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Holy Hydration! Face Cream",
    category: "beauty", subcategory: "Moisturizer", price: 13, image: img("elf-holy-hydration-cream"),
    rating: 4.6, reviewCount: 28300,
    description: "Rich hyaluronic + peptide moisturizer — a Jet Lag-style hydrator for less.",
    targetUser: "Dry skin wanting affordable hydration",
    ingredients: ["Hyaluronic Acid", "Peptides", "Niacinamide"],
    attributes: { hydration: 88, luxuryLevel: "Budget" },
    slug: "elf-holy-hydration-face-cream",
  },
  {
    id: "farmacy-green-clean", brandId: "farmacy", brandName: "Farmacy", name: "Green Clean Makeup Removing Cleansing Balm",
    category: "beauty", subcategory: "Cleanser", price: 36, image: img("farmacy-green-clean"),
    rating: 4.6, reviewCount: 20400, isOriginal: true,
    description: "Cult cleansing balm that melts away makeup and SPF.",
    targetUser: "First cleanse for makeup wearers",
    ingredients: ["Sunflower & Ginger Oils", "Papaya Enzymes"],
    attributes: { cleansing: true, luxuryLevel: "Mid" },
    slug: "farmacy-green-clean-cleansing-balm",
  },
  {
    id: "banila-clean-it-zero", brandId: "banila-co", brandName: "Banila Co", name: "Clean It Zero Cleansing Balm",
    category: "beauty", subcategory: "Cleanser", price: 19, image: img("banila-clean-it-zero"),
    rating: 4.6, reviewCount: 33100,
    description: "Best-selling K-beauty sherbet balm that dissolves makeup fast.",
    targetUser: "Makeup melt-off on a budget",
    ingredients: ["Acerola Extract", "Papaya Extract"],
    attributes: { cleansing: true, luxuryLevel: "Budget" },
    slug: "banila-co-clean-it-zero",
  },
  {
    id: "drunk-elephant-protini", brandId: "drunk-elephant", brandName: "Drunk Elephant", name: "Protini Polypeptide Cream",
    category: "beauty", subcategory: "Moisturizer", price: 68, image: img("drunk-elephant-protini"),
    rating: 4.5, reviewCount: 13700, isOriginal: true,
    description: "Protein-packed peptide cream that firms and improves skin tone.",
    targetUser: "Loss of firmness, dullness",
    ingredients: ["Signal Peptides", "Pygmy Waterlily", "Amino Acids"],
    attributes: { antiAging: true, hydration: 88 },
    slug: "drunk-elephant-protini-polypeptide-cream",
  },
  {
    id: "ordinary-buffet", brandId: "the-ordinary", brandName: "The Ordinary", name: "Buffet Multi-Technology Peptide Serum",
    category: "beauty", subcategory: "Serum", price: 15, image: img("ordinary-buffet"),
    rating: 4.4, reviewCount: 22900,
    description: "Multi-peptide serum targeting fine lines — a Protini-style peptide hit for less.",
    targetUser: "Anti-aging peptides on a budget",
    ingredients: ["Matrixyl 3000", "Argireline", "Hyaluronic Acid"],
    attributes: { antiAging: true, hydration: 84 },
    slug: "the-ordinary-buffet-peptide-serum",
  },

  // ===== MAKEUP =====
  {
    id: "ud-all-nighter", brandId: "urban-decay", brandName: "Urban Decay", name: "All Nighter Long-Lasting Setting Spray",
    category: "beauty", subcategory: "Setting Spray", price: 35, image: img("ud-all-nighter"),
    rating: 4.6, reviewCount: 39800, isOriginal: true,
    description: "The benchmark 16-hour makeup-locking setting spray.",
    targetUser: "All-day makeup wear",
    attributes: { longevity: "16h", finish: "Natural" },
    slug: "urban-decay-all-nighter-setting-spray",
  },
  {
    id: "elf-stay-all-night", brandId: "elf", brandName: "e.l.f. Cosmetics", name: "Stay All Night Setting Spray",
    category: "beauty", subcategory: "Setting Spray", price: 9, image: img("elf-stay-all-night"),
    rating: 4.5, reviewCount: 21500,
    description: "Long-wear setting spray that locks makeup — the All Nighter dupe.",
    targetUser: "All-day wear on a budget",
    attributes: { longevity: "16h", finish: "Natural" },
    slug: "elf-stay-all-night-setting-spray",
  },
  {
    id: "laura-mercier-powder", brandId: "laura-mercier", brandName: "Laura Mercier", name: "Translucent Loose Setting Powder",
    category: "beauty", subcategory: "Setting Powder", price: 43, image: img("laura-mercier-powder"),
    rating: 4.7, reviewCount: 28600, isOriginal: true,
    description: "Iconic translucent powder that sets makeup without flashback.",
    targetUser: "Long-lasting, shine-free finish",
    attributes: { finish: "Matte", flashback: false },
    slug: "laura-mercier-translucent-setting-powder",
  },
  {
    id: "coty-airspun", brandId: "coty", brandName: "Coty", name: "Airspun Loose Face Powder",
    category: "beauty", subcategory: "Setting Powder", price: 9, image: img("coty-airspun"),
    rating: 4.5, reviewCount: 47200,
    description: "Vintage cult loose powder for a smooth matte set — a Laura Mercier dupe.",
    targetUser: "Matte set on a tiny budget",
    attributes: { finish: "Matte", flashback: false },
    slug: "coty-airspun-loose-face-powder",
  },
  {
    id: "fenty-profiltr", brandId: "fenty", brandName: "Fenty Beauty", name: "Pro Filt'r Soft Matte Longwear Foundation",
    category: "beauty", subcategory: "Foundation", price: 40, image: img("fenty-profiltr"),
    rating: 4.5, reviewCount: 51200, isOriginal: true,
    description: "Soft-matte, buildable foundation famous for its huge shade range.",
    targetUser: "Medium-full coverage, long wear",
    attributes: { coverage: "Medium-Full", finish: "Soft Matte" },
    slug: "fenty-pro-filtr-soft-matte-foundation",
  },
  {
    id: "maybelline-fitme-foundation", brandId: "maybelline", brandName: "Maybelline", name: "Fit Me Matte + Poreless Foundation",
    category: "beauty", subcategory: "Foundation", price: 9, image: img("maybelline-fitme-foundation"),
    rating: 4.5, reviewCount: 73400,
    description: "Best-selling matte drugstore foundation — a Pro Filt'r alternative.",
    targetUser: "Normal-oily skin, everyday coverage",
    attributes: { coverage: "Medium", finish: "Matte" },
    slug: "maybelline-fit-me-matte-poreless-foundation",
  },
  {
    id: "loreal-infallible-foundation", brandId: "loreal", brandName: "L'Oréal Paris", name: "Infallible 24H Fresh Wear Foundation",
    category: "beauty", subcategory: "Foundation", price: 17, image: img("loreal-infallible-foundation"),
    rating: 4.4, reviewCount: 38900,
    description: "Lightweight, long-wear foundation with buildable medium coverage.",
    targetUser: "Long wear, natural-radiant finish",
    attributes: { coverage: "Medium", finish: "Natural" },
    slug: "loreal-infallible-24h-fresh-wear-foundation",
  },
  {
    id: "abh-dipbrow", brandId: "anastasia", brandName: "Anastasia Beverly Hills", name: "Dipbrow Pomade",
    category: "beauty", subcategory: "Brow", price: 25, image: img("abh-dipbrow"),
    rating: 4.6, reviewCount: 26700, isOriginal: true,
    description: "Waterproof brow pomade for bold, defined, long-lasting brows.",
    targetUser: "Full, sculpted brows",
    attributes: { finish: "Defined", waterproof: true },
    slug: "anastasia-dipbrow-pomade",
  },
  {
    id: "nyx-tame-frame", brandId: "nyx", brandName: "NYX", name: "Tame & Frame Tinted Brow Pomade",
    category: "beauty", subcategory: "Brow", price: 10, image: img("nyx-tame-frame"),
    rating: 4.4, reviewCount: 18900,
    description: "Waterproof tinted brow pomade — the Dipbrow dupe.",
    targetUser: "Defined brows on a budget",
    attributes: { finish: "Defined", waterproof: true },
    slug: "nyx-tame-and-frame-brow-pomade",
  },
  {
    id: "mac-velvet-teddy", brandId: "mac", brandName: "MAC Cosmetics", name: "Matte Lipstick in Velvet Teddy",
    category: "beauty", subcategory: "Lipstick", price: 24, image: img("mac-velvet-teddy"),
    rating: 4.7, reviewCount: 34800, isOriginal: true,
    description: "The iconic '90s deep-beige nude matte lipstick.",
    targetUser: "Everyday MLBB nude lovers",
    attributes: { finish: "Matte", shade: "Beige Nude" },
    slug: "mac-velvet-teddy-lipstick",
  },
  {
    id: "nyx-stockholm", brandId: "nyx", brandName: "NYX", name: "Soft Matte Lip Cream in Stockholm",
    category: "beauty", subcategory: "Lipstick", price: 7, image: img("nyx-stockholm"),
    rating: 4.4, reviewCount: 21100,
    description: "Creamy matte nude lip cream — a Velvet Teddy alternative.",
    targetUser: "Nude matte lips for less",
    attributes: { finish: "Matte", shade: "Beige Nude" },
    slug: "nyx-soft-matte-lip-cream-stockholm",
  },

  // ===== HAIR =====
  {
    id: "dyson-airwrap", brandId: "dyson", brandName: "Dyson", name: "Airwrap Multi-Styler Complete",
    category: "hair", subcategory: "Styling Tool", price: 599, image: img("dyson-airwrap"),
    rating: 4.6, reviewCount: 28900, isOriginal: true,
    description: "The coveted multi-styler that curls, smooths, and volumizes with air.",
    targetUser: "Salon styling at home, heat-conscious",
    attributes: { type: "Multi-styler", heatControl: true },
    slug: "dyson-airwrap-multi-styler-complete",
  },
  {
    id: "shark-flexstyle", brandId: "shark", brandName: "Shark Beauty", name: "FlexStyle Air Styling & Drying System",
    category: "hair", subcategory: "Styling Tool", price: 299, image: img("shark-flexstyle"),
    rating: 4.5, reviewCount: 21300,
    description: "Multi-styler that dries and styles with air — the Airwrap's top rival at half the price.",
    targetUser: "Airwrap results for less",
    attributes: { type: "Multi-styler", heatControl: true },
    slug: "shark-flexstyle-air-styling-system",
  },
  {
    id: "revlon-onestep", brandId: "revlon", brandName: "Revlon", name: "One-Step Volumizer PLUS 2.0",
    category: "hair", subcategory: "Styling Tool", price: 60, image: img("revlon-onestep"),
    rating: 4.5, reviewCount: 64200,
    description: "Viral hot-air brush that dries and volumizes in one step.",
    targetUser: "Quick blowout volume on a budget",
    attributes: { type: "Hot-air brush", heatControl: false },
    slug: "revlon-one-step-volumizer-plus-2",
  },
  {
    id: "olaplex-4p", brandId: "olaplex", brandName: "Olaplex", name: "No.4P Blonde Enhancer Toning Shampoo",
    category: "hair", subcategory: "Shampoo", price: 30, image: img("olaplex-4p"),
    rating: 4.5, reviewCount: 12100, isOriginal: true,
    description: "Purple bond-building shampoo that brightens blonde and removes brass.",
    targetUser: "Blonde, silver, or highlighted hair",
    ingredients: ["Bis-Aminopropyl Diglycol Dimaleate", "Violet Pigments"],
    attributes: { toning: true, purple: true, bondBuilding: true },
    slug: "olaplex-no4p-blonde-toning-shampoo",
  },
  {
    id: "fanola-no-yellow", brandId: "fanola", brandName: "Fanola", name: "No Yellow Purple Shampoo",
    category: "hair", subcategory: "Shampoo", price: 14, image: img("fanola-no-yellow"),
    rating: 4.5, reviewCount: 38600,
    description: "Intensely pigmented purple shampoo that kills brass fast — a cult budget toner.",
    targetUser: "Blonde/grey hair fighting brass",
    ingredients: ["Violet Pigments", "Surfactants"],
    attributes: { toning: true, purple: true, bondBuilding: false },
    slug: "fanola-no-yellow-purple-shampoo",
  },
  {
    id: "olaplex-7", brandId: "olaplex", brandName: "Olaplex", name: "No.7 Bonding Oil",
    category: "hair", subcategory: "Oil", price: 30, image: img("olaplex-7"),
    rating: 4.7, reviewCount: 19400, isOriginal: true,
    description: "Weightless reparative styling oil that adds shine and heat protection.",
    targetUser: "Damaged hair wanting shine + protection",
    ingredients: ["Bis-Aminopropyl Diglycol Dimaleate", "Shine Complex"],
    attributes: { bondBuilding: true, shine: 92, heatProtect: true },
    slug: "olaplex-no7-bonding-oil",
  },
  {
    id: "color-wow-dreamcoat", brandId: "color-wow", brandName: "Color Wow", name: "Dream Coat Supernatural Spray",
    category: "hair", subcategory: "Styling", price: 28, image: img("color-wow-dreamcoat"),
    rating: 4.4, reviewCount: 22700, isOriginal: true,
    description: "Heat-activated spray that makes hair glassy, smooth, and humidity-proof.",
    targetUser: "Frizz-prone hair in humidity",
    attributes: { frizzControl: true, antiHumidity: true },
    slug: "color-wow-dream-coat-supernatural-spray",
  },
  {
    id: "mielle-rosemary", brandId: "mielle", brandName: "Mielle Organics", name: "Rosemary Mint Scalp & Hair Strengthening Oil",
    category: "hair", subcategory: "Oil", price: 10, image: img("mielle-rosemary"),
    rating: 4.5, reviewCount: 71800,
    description: "Viral rosemary-mint oil that nourishes the scalp and supports growth.",
    targetUser: "Scalp care and hair growth",
    ingredients: ["Rosemary Oil", "Mint", "Biotin"],
    attributes: { scalp: true, growth: true },
    slug: "mielle-rosemary-mint-scalp-oil",
  },

  // ===== JEWELRY =====
  {
    id: "cartier-trinity", brandId: "cartier", brandName: "Cartier", name: "Trinity Ring",
    category: "jewelry", subcategory: "Ring", price: 1290, image: img("cartier-trinity"),
    rating: 4.9, reviewCount: 1500, isOriginal: true,
    description: "Three interlocking bands of rose, yellow, and white gold — a timeless icon.",
    targetUser: "Luxury ring collectors",
    attributes: { metal: "18k Tri-Gold", style: "Interlocking", occasion: "Everyday/Gift" },
    slug: "cartier-trinity-ring",
  },
  {
    id: "mejuri-dome-set", brandId: "mejuri", brandName: "Mejuri", name: "Bold Stackers Ring Set",
    category: "jewelry", subcategory: "Ring", price: 120, image: img("mejuri-dome-set"),
    rating: 4.5, reviewCount: 1700,
    description: "Stackable gold vermeil bands for a layered, interlocking look.",
    targetUser: "Trinity-inspired stacking on a mid budget",
    attributes: { metal: "18k Gold Vermeil", style: "Stacking", occasion: "Everyday" },
    slug: "mejuri-bold-stackers-ring-set",
  },
  {
    id: "baublebar-trinity", brandId: "baublebar", brandName: "BaubleBar", name: "Interlocking Trio Ring",
    category: "jewelry", subcategory: "Ring", price: 42, image: img("baublebar-trinity"),
    rating: 4.2, reviewCount: 980,
    description: "Three-tone interlocking bands — a Trinity-inspired ring for less.",
    targetUser: "Trinity look on a budget",
    attributes: { metal: "Gold Plated", style: "Interlocking", occasion: "Everyday" },
    slug: "baublebar-interlocking-trio-ring",
  },
  {
    id: "jennifer-fisher-hoops", brandId: "jennifer-fisher", brandName: "Jennifer Fisher", name: "Lilly Hoops",
    category: "jewelry", subcategory: "Earrings", price: 325, image: img("jennifer-fisher-hoops"),
    rating: 4.8, reviewCount: 620, isOriginal: true,
    description: "The celebrity-favorite chunky gold hoops with serious presence.",
    targetUser: "Statement-hoop devotees",
    attributes: { metal: "Gold Plated Brass", style: "Chunky Hoops", occasion: "Everyday/Statement" },
    slug: "jennifer-fisher-lilly-hoops",
  },
  {
    id: "mejuri-bold-hoops", brandId: "mejuri", brandName: "Mejuri", name: "Bold Hoops",
    category: "jewelry", subcategory: "Earrings", price: 120, image: img("mejuri-bold-hoops"),
    rating: 4.5, reviewCount: 2300,
    description: "Chunky gold vermeil hoops with a luxe, weighty feel.",
    targetUser: "Statement hoops, fine-jewelry quality",
    attributes: { metal: "18k Gold Vermeil", style: "Chunky Hoops", occasion: "Everyday" },
    slug: "mejuri-bold-hoops",
  },
  {
    id: "baublebar-hoops", brandId: "baublebar", brandName: "BaubleBar", name: "Mini Gold Hoops",
    category: "jewelry", subcategory: "Earrings", price: 36, image: img("baublebar-hoops"),
    rating: 4.3, reviewCount: 1900,
    description: "Everyday gold-tone hoops — a chunky-hoop look for less.",
    targetUser: "Affordable everyday hoops",
    attributes: { metal: "Gold Plated", style: "Hoops", occasion: "Everyday" },
    slug: "baublebar-mini-gold-hoops",
  },
  {
    id: "kay-tennis", brandId: "kay", brandName: "Kay Jewelers", name: "Diamond Tennis Necklace (4 ct)",
    category: "jewelry", subcategory: "Necklace", price: 1995, image: img("kay-tennis"),
    rating: 4.7, reviewCount: 540, isOriginal: true,
    description: "Classic 14k white-gold diamond tennis necklace with continuous sparkle.",
    targetUser: "Fine-jewelry tennis necklace buyers",
    attributes: { metal: "14k White Gold", stone: "Diamond", style: "Tennis" },
    slug: "kay-diamond-tennis-necklace",
  },
  {
    id: "baublebar-tennis", brandId: "baublebar", brandName: "BaubleBar", name: "Cubic Zirconia Tennis Necklace",
    category: "jewelry", subcategory: "Necklace", price: 58, image: img("baublebar-tennis"),
    rating: 4.4, reviewCount: 3100,
    description: "Sparkling CZ tennis necklace — the diamond-tennis look for a fraction of the price.",
    targetUser: "Tennis-necklace sparkle on a budget",
    attributes: { metal: "Rhodium Plated", stone: "Cubic Zirconia", style: "Tennis" },
    slug: "baublebar-cz-tennis-necklace",
  },
];

// ── Offers ─────────────────────────────────────────────────────
const a = (q: string) => `https://www.amazon.com/s?k=${encodeURIComponent(q)}`;
const seph = (q: string) => `https://www.sephora.com/search?keyword=${encodeURIComponent(q)}`;
const ulta = (q: string) => `https://www.ulta.com/shop/search?Ntt=${encodeURIComponent(q)}`;
const tgt = (q: string) => `https://www.target.com/s?searchTerm=${encodeURIComponent(q)}`;
const nord = (q: string) => `https://www.nordstrom.com/sr?keyword=${encodeURIComponent(q)}`;

export const EXTRA2_OFFER_SPECS: Record<string, OfferSpec[]> = {
  "paulas-choice-bha": [{ retailerId: "sephora", url: seph("paulas choice 2 bha"), price: 35 }, { retailerId: "amazon", url: a("Paulas Choice 2% BHA Liquid Exfoliant"), price: 35 }],
  "cosrx-bha": [{ retailerId: "amazon", url: a("COSRX BHA Blackhead Power Liquid"), price: 25 }, { retailerId: "ulta", url: ulta("cosrx bha"), price: 25 }],
  "supergoop-glowscreen": [{ retailerId: "sephora", url: seph("supergoop glowscreen"), price: 38 }],
  "elf-whoa-glow": [{ retailerId: "target", url: tgt("elf whoa glow spf"), price: 14 }, { retailerId: "ulta", url: ulta("elf whoa glow"), price: 14 }],
  "summer-fridays-jetlag": [{ retailerId: "sephora", url: seph("summer fridays jet lag mask"), price: 49 }],
  "elf-holy-hydration-cream": [{ retailerId: "target", url: tgt("elf holy hydration face cream"), price: 13 }, { retailerId: "amazon", url: a("elf Holy Hydration Face Cream"), price: 13 }],
  "farmacy-green-clean": [{ retailerId: "sephora", url: seph("farmacy green clean balm"), price: 36 }],
  "banila-clean-it-zero": [{ retailerId: "amazon", url: a("Banila Co Clean It Zero"), price: 19 }, { retailerId: "ulta", url: ulta("banila clean it zero"), price: 19 }],
  "drunk-elephant-protini": [{ retailerId: "sephora", url: seph("drunk elephant protini"), price: 68 }],
  "ordinary-buffet": [{ retailerId: "sephora", url: seph("the ordinary buffet"), price: 15 }, { retailerId: "ulta", url: ulta("the ordinary buffet"), price: 15 }],

  "ud-all-nighter": [{ retailerId: "sephora", url: seph("urban decay all nighter setting spray"), price: 35 }, { retailerId: "ulta", url: ulta("urban decay all nighter"), price: 35 }],
  "elf-stay-all-night": [{ retailerId: "target", url: tgt("elf stay all night setting spray"), price: 9 }, { retailerId: "amazon", url: a("elf Stay All Night Setting Spray"), price: 9 }],
  "laura-mercier-powder": [{ retailerId: "sephora", url: seph("laura mercier translucent setting powder"), price: 43 }, { retailerId: "nordstrom", url: nord("laura mercier translucent powder"), price: 43 }],
  "coty-airspun": [{ retailerId: "amazon", url: a("Coty Airspun Loose Face Powder"), price: 9 }, { retailerId: "target", url: tgt("coty airspun powder"), price: 9 }],
  "fenty-profiltr": [{ retailerId: "sephora", url: seph("fenty pro filtr foundation"), price: 40 }],
  "maybelline-fitme-foundation": [{ retailerId: "target", url: tgt("maybelline fit me matte poreless foundation"), price: 9 }, { retailerId: "amazon", url: a("Maybelline Fit Me Matte Poreless Foundation"), price: 9 }],
  "loreal-infallible-foundation": [{ retailerId: "target", url: tgt("loreal infallible fresh wear foundation"), price: 17 }, { retailerId: "ulta", url: ulta("loreal infallible fresh wear"), price: 17 }],
  "abh-dipbrow": [{ retailerId: "sephora", url: seph("anastasia dipbrow pomade"), price: 25 }],
  "nyx-tame-frame": [{ retailerId: "ulta", url: ulta("nyx tame and frame brow pomade"), price: 10 }, { retailerId: "amazon", url: a("NYX Tame Frame Brow Pomade"), price: 10 }],
  "mac-velvet-teddy": [{ retailerId: "sephora", url: seph("mac velvet teddy"), price: 24 }, { retailerId: "nordstrom", url: nord("mac velvet teddy lipstick"), price: 24 }],
  "nyx-stockholm": [{ retailerId: "ulta", url: ulta("nyx soft matte lip cream stockholm"), price: 7 }, { retailerId: "amazon", url: a("NYX Soft Matte Lip Cream Stockholm"), price: 7 }],

  "dyson-airwrap": [{ retailerId: "sephora", url: seph("dyson airwrap"), price: 599 }, { retailerId: "ulta", url: ulta("dyson airwrap"), price: 599 }],
  "shark-flexstyle": [{ retailerId: "amazon", url: a("Shark FlexStyle Air Styling System"), price: 299 }, { retailerId: "target", url: tgt("shark flexstyle"), price: 299 }],
  "revlon-onestep": [{ retailerId: "amazon", url: a("Revlon One Step Volumizer Plus 2.0"), price: 60 }, { retailerId: "target", url: tgt("revlon one step volumizer"), price: 60 }],
  "olaplex-4p": [{ retailerId: "sephora", url: seph("olaplex 4p purple shampoo"), price: 30 }, { retailerId: "amazon", url: a("Olaplex No 4P Blonde Toning Shampoo"), price: 30 }],
  "fanola-no-yellow": [{ retailerId: "amazon", url: a("Fanola No Yellow Purple Shampoo"), price: 14 }],
  "olaplex-7": [{ retailerId: "sephora", url: seph("olaplex no 7 bonding oil"), price: 30 }, { retailerId: "amazon", url: a("Olaplex No 7 Bonding Oil"), price: 30 }],
  "color-wow-dreamcoat": [{ retailerId: "sephora", url: seph("color wow dream coat"), price: 28 }, { retailerId: "amazon", url: a("Color Wow Dream Coat Supernatural Spray"), price: 28 }],
  "mielle-rosemary": [{ retailerId: "target", url: tgt("mielle rosemary mint scalp oil"), price: 10 }, { retailerId: "amazon", url: a("Mielle Rosemary Mint Scalp Oil"), price: 10 }],

  "cartier-trinity": [{ retailerId: "amazon", url: a("Cartier Trinity Ring"), price: 1290 }],
  "mejuri-dome-set": [{ retailerId: "mejuri", url: "https://www.mejuri.com/shop/products/bold-stackers", price: 120 }],
  "baublebar-trinity": [{ retailerId: "amazon", url: a("BaubleBar interlocking trio ring gold"), price: 42 }],
  "jennifer-fisher-hoops": [{ retailerId: "nordstrom", url: nord("jennifer fisher lilly hoops"), price: 325 }],
  "mejuri-bold-hoops": [{ retailerId: "mejuri", url: "https://www.mejuri.com/shop/products/bold-hoops", price: 120 }],
  "baublebar-hoops": [{ retailerId: "amazon", url: a("BaubleBar mini gold hoops"), price: 36 }],
  "kay-tennis": [{ retailerId: "amazon", url: a("Kay diamond tennis necklace 14k"), price: 1995 }],
  "baublebar-tennis": [{ retailerId: "amazon", url: a("BaubleBar cubic zirconia tennis necklace"), price: 58 }],
};

// ── Dupe relationships ─────────────────────────────────────────
export const EXTRA2_ALTERNATIVES: Record<string, Alternative[]> = {
  "paulas-choice-bha": [
    { productId: "cosrx-bha", matchScore: 86, dupeLevel: "budget", reason: "BHA exfoliation with niacinamide, gentler and cheaper" },
  ],
  "supergoop-glowscreen": [
    { productId: "elf-whoa-glow", matchScore: 90, dupeLevel: "budget", reason: "Glowy SPF primer-sunscreen, ~3× cheaper" },
  ],
  "summer-fridays-jetlag": [
    { productId: "elf-holy-hydration-cream", matchScore: 85, dupeLevel: "budget", reason: "Rich hyaluronic hydration for a fraction of the price" },
  ],
  "farmacy-green-clean": [
    { productId: "banila-clean-it-zero", matchScore: 88, dupeLevel: "budget", reason: "Cult cleansing balm that melts makeup, half the price" },
  ],
  "drunk-elephant-protini": [
    { productId: "ordinary-buffet", matchScore: 84, dupeLevel: "budget", reason: "Multi-peptide anti-aging serum, ~4× cheaper" },
  ],
  "ud-all-nighter": [
    { productId: "elf-stay-all-night", matchScore: 89, dupeLevel: "budget", reason: "16-hour makeup lock for under $10 — the classic dupe" },
  ],
  "laura-mercier-powder": [
    { productId: "coty-airspun", matchScore: 85, dupeLevel: "budget", reason: "Smooth matte translucent set, ~5× cheaper" },
  ],
  "fenty-profiltr": [
    { productId: "maybelline-fitme-foundation", matchScore: 86, dupeLevel: "budget", reason: "Soft-matte medium coverage, drugstore price" },
    { productId: "loreal-infallible-foundation", matchScore: 83, dupeLevel: "budget", reason: "Long-wear buildable coverage for less" },
  ],
  "abh-dipbrow": [
    { productId: "nyx-tame-frame", matchScore: 88, dupeLevel: "budget", reason: "Waterproof tinted brow pomade, less than half the price" },
  ],
  "mac-velvet-teddy": [
    { productId: "nyx-stockholm", matchScore: 84, dupeLevel: "budget", reason: "Creamy beige-nude matte, a longtime Velvet Teddy dupe" },
  ],
  "dyson-airwrap": [
    { productId: "shark-flexstyle", matchScore: 88, dupeLevel: "premium", reason: "Multi-styler with comparable results at half the price" },
    { productId: "revlon-onestep", matchScore: 78, dupeLevel: "budget", reason: "One-step volumizing blowout for a fraction of the cost" },
  ],
  "olaplex-4p": [
    { productId: "fanola-no-yellow", matchScore: 84, dupeLevel: "budget", reason: "Intense purple toning that kills brass, ~2× cheaper" },
  ],
  "olaplex-7": [
    { productId: "moroccanoil-treatment", matchScore: 80, dupeLevel: "similar", reason: "Shine + frizz control finishing oil" },
    { productId: "verb-ghost-oil", matchScore: 77, dupeLevel: "budget", reason: "Weightless shine oil at a lower price" },
  ],
  "cartier-trinity": [
    { productId: "mejuri-dome-set", matchScore: 80, dupeLevel: "similar", reason: "Stacked gold vermeil bands for an interlocking look" },
    { productId: "baublebar-trinity", matchScore: 78, dupeLevel: "budget", reason: "Three-tone interlocking bands at an accessible price" },
  ],
  "jennifer-fisher-hoops": [
    { productId: "mejuri-bold-hoops", matchScore: 85, dupeLevel: "similar", reason: "Chunky gold vermeil hoops, fine-jewelry quality for less" },
    { productId: "baublebar-hoops", matchScore: 79, dupeLevel: "budget", reason: "Everyday chunky-hoop look at a budget price" },
  ],
  "kay-tennis": [
    { productId: "baublebar-tennis", matchScore: 82, dupeLevel: "budget", reason: "CZ tennis necklace with the same sparkle, ~30× cheaper" },
  ],
};
