import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Affiliate Disclosure — DupeDose",
  description: "How DupeDose makes money and our affiliate relationships.",
};

export default function DisclosurePage() {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <p className="text-xs font-semibold uppercase tracking-widest mb-2" style={{ color: "var(--rose)", fontFamily: "system-ui, sans-serif" }}>
        Transparency
      </p>
      <h1 style={{ fontSize: "2rem", fontFamily: "Georgia, serif", fontWeight: 700, marginBottom: "1.5rem" }}>
        Affiliate Disclosure
      </h1>
      <div style={{ fontFamily: "system-ui, sans-serif", color: "var(--muted)", lineHeight: 1.8, fontSize: "0.95rem" }}>
        <p className="mb-4" style={{ color: "var(--foreground)", fontWeight: 600 }}>
          As an Amazon Associate, DupeDose earns from qualifying purchases.
        </p>
        <p className="mb-4">
          DupeDose is a participant in the Amazon Services LLC Associates Program, an affiliate advertising
          program designed to provide a means for sites to earn advertising fees by advertising and linking to
          Amazon.com. We also participate in other affiliate programs (such as Skimlinks, Rakuten, and Impact).
        </p>
        <p className="mb-4">
          DupeDose is a free product-discovery engine. We help you find alternatives and dupes
          for beauty, hair care, and jewelry products — and we keep the lights on through
          affiliate commissions.
        </p>
        <p className="mb-4">
          When you click a &ldquo;View Deal&rdquo; button and make a purchase at a retailer such as
          Amazon, Sephora, Ulta, Target, or a brand&rsquo;s own site, we may earn a small commission.
          <strong style={{ color: "var(--foreground)" }}> This never costs you anything extra.</strong>
        </p>
        <p className="mb-4">
          Our match scores and recommendations are generated by our analysis engine based on
          ingredients, attributes, and product data — not by how much a retailer pays. Prices shown
          are for reference and may change; always confirm the current price on the retailer&rsquo;s site.
        </p>
        <p>
          As an Amazon Associate and a member of other affiliate programs, DupeDose earns from
          qualifying purchases.
        </p>
      </div>
    </div>
  );
}
